# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Classe virtuale di Play with Docker"
email: 
description: > # this means to ignore newlines until "baseurl:"
  Play with docker tutorials
  
baseurl: # the subpath of your site, e.g. /blog
url: "https://training.play-with-docker.com" # the base hostname & protocol for your site

#sidebar
default-image: docker-logo.svg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: PWD Team
copyright:
   name: Docker, Inc.
   link: 'https://docker.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Sass style
sass:
  style: compressed

# Gems
gems: [jekyll-paginate]

# Plugins
plugins_dir:
  - jekyll-paginate

# Play with Docker
pwdurl: https://labs.play-with-docker.com
