version: '3'

services:

  jekyll:
    image: jekyll/jekyll:3
    restart: always
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
    command: ["jekyll", "serve"]  
    env_file:
      - global-variables.env
