version: '3'

services:

  jekyll:
    image: jekyll/jekyll:3
    restart: always
    volumes:
      - ./:/srv/jekyll
    ports:
      - 4000:4000
    command: ["jekyll", "serve"]

#This service is just for building the site
#  build:
#    image: jekyll/jekyll:3
#    volumes:
#      - ./:/srv/jekyll
#    command: "jekyll b"
